nginx:
  build: ./nginx/
  container_name: nginx-container-new
  ports:
    - 80:80
  links:
    - php
  volumes_from:
    - app-data

php:
  build: ./php/
  container_name: php-container
  expose:
    - 9000
  links:
    - mysql
  volumes_from:
    - app-data

app-data:
  image: php:7.0-fpm
  container_name: app-data-container
  volumes:
    - ./www/html/:/var/www/html/
  command: "true"

mysql:
  image: mysql:5.7
  container_name: mysql-container
  command: --default-authentication-plugin=mysql_native_password
  restart: always
  ports:
    - 3306:3306
  volumes_from:
    - mysql-data
  environment:
    MYSQL_ROOT_PASSWORD: secret
    MYSQL_DATABASE: mydb
    MYSQL_USER: myuser
    MYSQL_PASSWORD: password

mysql-data:
  image: mysql:5.7
  container_name: mysql-data-container
  volumes:
    #- /var/lib/mysql
    - ./mysql:/docker-entrypoint-initdb.d
  command: "true"
